SHOW DATABASES;

CREATE DATABASE STUDENTdatabase;
USE STUDENTdatabase;
CREATE TABLE STUDENT (
    stid INT(5) PRIMARY KEY,
    stname VARCHAR(20),
    dob DATE,
    doj DATE,
    fee INT(5),
    gender CHAR(1)
);

INSERT INTO me (stid, stname, dob, doj, fee, gender)
VALUES (1, 'SHAREEF', '2001-01-10', '2001-10-05', 10000, 'M');

INSERT INTO me (stid, stname, dob, doj, fee, gender)
VALUES (2, 'NADEEM', '2019-11-30', '2021-10-26', 11000, 'M');
SELECT * FROM STUDENT;

DESC STUDENT;
ALTER TABLE STUDENT ADD phone_no VARCHAR(15);
SELECT * FROM STUDENT;

ALTER TABLE STUDENT
CHANGE phone_no student_no VARCHAR(15);
SELECT * FROM STUDENT;


RENAME TABLE STUDENT TO STUDENT_INFO;

ALTER TABLE STUDENT_INFO DROP COLUMN fee; 

SELECT * FROM STUDENT_INFO;

DELETE FROM STUDENT_INFO WHERE stid = 2;

SELECT * FROM STUDENT_INFO;